name: Keep Git Green

on:
  schedule:
    - cron: '0 8 * * *'  # 15:00 WIB
    - cron: '0 12 * * *'  # 16:00 WIB
    - cron: '0 13 * * *' # 17:00 WIB
    - cron: '0 14 * * *' # 18:00 WIB
    - cron: '0 15 * * *' # 19:00 WIB

jobs:
  update-streak:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Update file to trigger commit
      run: |
        echo "Update on $(date)" >> streak.txt
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'Adib-F'
        git config --global user.email 'fakhrimuhammadadib@gmail.com'
        git add streak.txt
        git commit -m "Keep streak green on $(date)"
        git push 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 HEAD:main
