name: Keep Git Green

on:
  schedule:
    - cron: '0 14 * * *'  # 15:00 WIB
    - cron: '0 15 * * *'  # 16:00 WIB
    - cron: '0 16 * * *' # 17:00 WIB
    - cron: '0 17 * * *' # 18:00 WIB
    - cron: '0 18 * * *' # 19:00 WIB

jobs:
  update-streak:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Update file to trigger commit
      run: |
        echo "Update on $(date)" >> streak.txt
        
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'Adib-F'
        git config --global user.email 'fakhrimuhammadadib@gmail.com'
        git add streak.txt
        git commit -m "Keep streak green on $(date)"
        git push
